# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PzTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PzTest
  pod 'Alamofire'
  pod 'SwiftyJSON'
  

  target 'PzTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PzTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
